services:
  dst-server:
    image: jamesits/dst-server:latest
    container_name: dst-server
    restart: unless-stopped
    entrypoint:
      - /bin/bash
      - -lc
      - |
        chmod 711 /root
        exec /usr/local/bin/entrypoint.sh "$$@"
      - dst-entrypoint
    command:
      - supervisord
      - -c
      - /etc/supervisor/supervisor.conf
      - -n
    environment:
      DST_SERVER_ARCH: amd64
    ports:
      - "10999-11000:10999-11000/udp"
      - "12346-12347:12346-12347/udp"
    volumes:
      - ./data:/data
      - ./server:/opt/dst_server
      - ./steam:/root/Steam
    stop_grace_period: 6m